In [29]:
import pandas as pd

# Biblioteca que faz chamada para o Google Drive
from google.colab import drive

# Isso solicitará autorização com a sua conta do Google Drive
drive.mount('/content/drive')

# Cria a variável data e lê o arquivo csv, index_col = 0 retira a coluna de índices, parse_dates = true diz quais colunas devem ser interpretadas como data
data = pd.read_csv("/content/drive/My Drive/Notebooks/AAPL.csv", index_col=0, parse_dates=True)

# Mostra as primeiras linhas do dataset
data.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

                 Open       High        Low      Close  Adj Close     Volume
Date
2020-01-27  77.514999  77.942497  76.220001  77.237503  76.576187  161940000
2020-01-28  78.150002  79.599998  78.047501  79.422501  78.742477  162234000
2020-01-29  81.112503  81.962502  80.345001  81.084999  80.390747  216229200
2020-01-30  80.135002  81.022499  79.687500  80.967499  80.274246  126743200
2020-01-31  80.232498  80.669998  77.072502  77.377502  76.714989  199588400

In [30]:
# Mostra a diferença do valor entre o fechamento e início por data
daily_change = data['Close'] - data['Open']
daily_change

Date
2020-01-27   -0.277496
2020-01-28    1.272499
2020-01-29   -0.027504
2020-01-30    0.832497
2020-01-31   -2.854996
                ...
2021-01-20    3.369995
2021-01-21    3.069992
2021-01-22    2.790008
2021-01-25   -0.150009
2021-01-26   -1.520004
Length: 253, dtype: float64

In [32]:
# Percentual da diferença do valor entre o fechamento e o início por data
daily_change_percent = data['Close'] - data['Open'] / data['Open'] * 100
daily_change_percent

Date
2020-01-27   -22.762497
2020-01-28   -20.577499
2020-01-29   -18.915001
2020-01-30   -19.032501
2020-01-31   -22.622498
                ...
2021-01-20    32.029999
2021-01-21    36.869995
2021-01-22    39.070007
2021-01-25    42.919998
2021-01-26    42.080002
Length: 253, dtype: float64

In [31]:
# Mostra o crescimento do fechamento por data a partir da data inicial
norm = data['Close']/data['Close'].iloc[0]
norm

Date
2020-01-27    1.000000
2020-01-28    1.028289
2020-01-29    1.049814
2020-01-30    1.048293
2020-01-31    1.001813
                ...
2021-01-20    1.709403
2021-01-21    1.772067
2021-01-22    1.800550
2021-01-25    1.850396
2021-01-26    1.839521
Name: Close, Length: 253, dtype: float64

In [33]:
# Adicionando novas colunas com os calculos 
data ['daily_change'] = data['Close'] - data['Open']
data ['daily_change_percent'] = data['Close'] - data['Open'] / data['Open'] * 100
data ['norm'] = data['Close']/data['Close'].iloc[0]
data.head()

                 Open       High  ...  daily_change_percent      norm
Date                              ...
2020-01-27  77.514999  77.942497  ...            -22.762497  1.000000
2020-01-28  78.150002  79.599998  ...            -20.577499  1.028289
2020-01-29  81.112503  81.962502  ...            -18.915001  1.049814
2020-01-30  80.135002  81.022499  ...            -19.032501  1.048293
2020-01-31  80.232498  80.669998  ...            -22.622498  1.001813

[5 rows x 9 columns]

In [34]:
# Funções de min, max e media
min = data['Close'].min()
max = data['Close'].max()
mean = data['Close'].mean()
min,max,mean

(56.092499, 142.919998, 98.8017784426877)

In [40]:
# Excluindo colunas desnecessárias
data.drop(labels=['High', 'Low', 'Adj Close', 'Volume'], axis=1, inplace=True)
data.head()

                 Open      Close  daily_change  daily_change_percent      norm
Date
2020-01-27  77.514999  77.237503     -0.277496            -22.762497  1.000000
2020-01-28  78.150002  79.422501      1.272499            -20.577499  1.028289
2020-01-29  81.112503  81.084999     -0.027504            -18.915001  1.049814
2020-01-30  80.135002  80.967499      0.832497            -19.032501  1.048293
2020-01-31  80.232498  77.377502     -2.854996            -22.622498  1.001813

In [43]:
import matplotlib.pyplot as plt